name: jobs examples

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artfact for reuse
        run: echo "Full featured artifact" > build-result.txt
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: use article created
        run: ls build-result.txt
