name: jobs examples

on:
  push:
    branches: [ "main" ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step do job1
        run: echo Hello, world! job 1.
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step do job2
        run: echo Hello, world! job2.
