name: conchayoro-pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: echo "Configuração inicial do pipeline"
