name: Node.js 

on:
  push:
    branches: [ "main" ]

jobs:
  marketplace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: configuração do Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: verification of node version
      run: node --version
      
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
      - id: step-caller
        uses: "./.github/actions/hello"
        with:
          the-caller: 'Myself'
      - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
        shell: bash
